### ISSUE TITLE
Style file not found.

### ISSUE THREAD

**Issue by ThRintelen** [flakolefluk/tailwindcss-schematics#10]
i try ng add @flakolefluk/tailwind-schematics and got:

Installing packages for tooling via npm.
Installed packages for tooling via npm.
Style file not found.

Angular 10

**Comment by flakolefluk** [comment]
Hi @ThRintelen. I'll check tonight as i haven't tested this package with angular 10.
One question:  did you setup your project with scss, css, or something else?

**Comment by ThRintelen** [comment]
We use scss

**Comment by flakolefluk** [comment]
@ThRintelen The message appears because the file at src/styles.scss was not found. Did you change it's name or removed it? If so creating it, and making sure that the project is using it should fix it.
I released v 0.0.7-alpha.0 with proper support for v9 v10. and might add later better support when the file is not found (probably a better error message to and the option to create the file if it does not exist).
I tested the package pre-release with a new v10 project.
Thanks for filling this issue, let me know how it goes.
Also feel free to contribute and/or add suggestions.

**Comment by ThRintelen** [comment]
This is a part of my angular json for one project

`"styles": [
                            {
                                "input": "library/core/styles/bootstrap/styles-app-loading.scss",
                                "bundleName": "splash-screen"
                            },
                            "node_modules/flickity/dist/flickity.css",
                            "projects/traperto/examples/campus/src/app/styles/app.scss"
                        ],`
